<a href="https://colab.research.google.com/github/artemisIsNotBeam/3d-printer-website/blob/main/Soccer_player_salaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
import pandas as pd
import

# i need to import regression and train test split

In [24]:
data = pd.read_csv("drive/MyDrive/raw_wages.csv")
#data['Salary'] = data['Salary'].str[2:-5]
data['Salary'] = data['Salary'].str.replace(',', '')
data['Salary'] = data['Salary'].str.replace('p/a','')
data['Salary'] = data['Salary'].str.replace('€','').astype(float)

justPrem = data[data['Division'].str.contains('Premier')]

justPrem.head(10)

,Name,Club,Division,Based,Nat,EU National,Caps,AT Apps,Position,Age,CR,Begins,Expires,Last Club,Last Trans. Fee,Salary
15,- -,-,Premier League ...,England (Premier League) ...,BRA,Yes,21.0,327,,30.0,"8,864",15/8/2023,30/6/2028,Benfica,€41M,22733000.0
20,- -,-,Premier League ...,England (Premier League) ...,ENG,No,82.0,352,,28.0,"8,158",13/7/2022,30/6/2027,Man City,€55M,21225000.0
21,- -,-,Premier League ...,England (Premier League) ...,EGY,No,89.0,401,,31.0,"9,325",1/7/2022,30/6/2025,Roma,€40M,21225000.0
24,- -,-,Premier League ...,England (Premier League) ...,NOR,Yes,25.0,190,,23.0,"9,406",1/7/2022,30/6/2027,Dortmund,€59M,20619000.0
25,- -,-,Premier League ...,England (Premier League) ...,BEL,Yes,99.0,427,,32.0,"9,503",5/7/2021,30/6/2025,Wolfsburg,€63M,20619000.0
30,- -,-,Premier League ...,England (Premier League) ...,FRA,Yes,10.0,174,,25.0,"8,100",1/7/2023,30/6/2029,RB Leipzig,€60M,18193000.0
31,- -,-,Premier League ...,England (Premier League) ...,BRA,Yes,71.0,357,,31.0,"7,892",22/8/2022,30/6/2026,Real Madrid,€70M,18193000.0
32,- -,-,Premier League ...,England (Premier League) ...,ENG,No,53.0,241,,25.0,"8,003",18/7/2023,30/6/2028,,-,18193000.0
40,- -,-,Premier League ...,England (Premier League) ...,ENG,No,23.0,163,,23.0,"7,200",23/7/2021,30/6/2026,Dortmund,€85M,16677000.0
41,- -,-,Premier League ...,England (Premier League) ...,ENG,Yes,32.0,280,,27.0,"8,289",5/8/2021,30/6/2027,Aston Villa,€117M,16374000.0

In [27]:
y = justPrem['Salary']
x = justPrem[['EU National', 'Caps','AT Apps','CR','Age','Last Trans. Fee']]

x_train,y_train,x_test,y_test = train_test_split(x,y,.2)

NameError: name 'LinearRegression' is not defined